#!/usr/bin/env python3
"""Embed the prompt assets into a Python module compiled into the app binary.

The prompt/*.txt files remain the canonical, editable source in the repository.
This script bakes their current contents into src/prompt_data.py, which
PyInstaller compiles into the executable. The packaged app then contains no
loose plain-text prompt files next to the binary.

Run from the project root:
    python scripts/embed_prompts.py
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROMPT_DIR = ROOT / "prompt"
OUTPUT = ROOT / "src" / "prompt_data.py"

HEADER = '''# Generated by scripts/embed_prompts.py. DO NOT EDIT BY HAND.
# Run `python scripts/embed_prompts.py` after changing any file in prompt/.
# These strings are compiled into the app binary so the prompt assets are not
# shipped as loose files next to the executable.

PROMPT_FILES: dict[str, str] = {
'''


def main() -> int:
    entries = []
    for path in sorted(PROMPT_DIR.glob("*.txt")):
        content = path.read_text(encoding="utf-8").strip()
        entries.append(f"    {path.name!r}: {content!r},")
    body = HEADER + "\n".join(entries) + "\n}\n"
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"Embedded {len(entries)} prompt files -> {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
